/** @type {import("prettier").Config} */ module.exports = {
  semi: false,
  singleQuote: true,
  bracketSameLine: true,
  bracketSpacing: true,
  plugins: [
    '@ianvs/prettier-plugin-sort-imports',
    'prettier-plugin-tailwindcss',
  ],
  importOrder: [
    '^next(/.*)?$',
    '^react$',
    '^react(/.*)?$',
    '',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@/app(/.*)?$',
    '^@/components(/.*)?$',
    '^@/features(/.*)?$',
    '^@/hooks(/.*)?$',
    '^@/lib(/.*)?$',
    '',
    '.css$',
    '^(?!.*[.]css$)[./].*$',
    '',
    '<TYPES>',
    '<TYPES>^[.]',
  ],
}
